[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

[program:backend]
command=gunicorn config.wsgi:application --bind 127.0.0.1:8000
directory=/app/backend
autostart=true
autorestart=true
environment=DATABASE_URL=%(ENV_DATABASE_URL)s,SECRET_KEY=%(ENV_SECRET_KEY)s,DEBUG=%(ENV_DEBUG)s

[program:frontend]
command=npm start -- -p 3000
directory=/app/frontend
environment=NODE_ENV="production"
autostart=true
autorestart=true
