[supervisord]
nodaemon=true
user=root

# Запускаем Nginx
[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

# Запускаем бекенд FastAPI
[program:backend]
command=uvicorn main:app --host 127.0.0.1 --port 8000
directory=/app/backend
autostart=true
autorestart=true

# Запускаем Next.js фронтенд
[program:frontend]
command=npm start -- -p 3000
directory=/app/frontend
environment=NODE_ENV="production"
autostart=true
autorestart=true
