[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

[program:backend]
command=gunicorn config.wsgi:application --bind 127.0.0.1:8000
directory=/app/backend
autostart=true
autorestart=true
environment=DATABASE_URL="%(ENV_DATABASE_URL)s",SECRET_KEY="%(ENV_SECRET_KEY)s",DEBUG="%(ENV_DEBUG)s",DJANGO_SETTINGS_MODULE="my_settings",EMAIL_HOST_USER="%(ENV_EMAIL_HOST_USER)s",EMAIL_HOST_PASSWORD="%(ENV_EMAIL_HOST_PASSWORD)s",CELERY_BROKER_URL="%(ENV_CELERY_BROKER_URL)s",FRONTEND_URL="%(ENV_FRONTEND_URL)s"

[program:celery]
command=celery -A config worker -l info
directory=/app/backend
autostart=true
autorestart=true
environment=DATABASE_URL="%(ENV_DATABASE_URL)s",SECRET_KEY="%(ENV_SECRET_KEY)s",DJANGO_SETTINGS_MODULE="my_settings",EMAIL_HOST_USER="%(ENV_EMAIL_HOST_USER)s",EMAIL_HOST_PASSWORD="%(ENV_EMAIL_HOST_PASSWORD)s",CELERY_BROKER_URL="%(ENV_CELERY_BROKER_URL)s",FRONTEND_URL="%(ENV_FRONTEND_URL)s"

[program:frontend]
command=npm start -- -p 3000
directory=/app/frontend
autostart=true
autorestart=true
environment=NODE_ENV="production"
